### ISSUE TITLE
Keep words on same baseline

### ISSUE THREAD

**Issue by goodmami** [neocl/jamdict-web#6]
Words with ruby text get shoved down while other words stay on the baseline. This makes it difficult to read. Illustrated below:

![baseline](https://user-images.githubusercontent.com/1428419/120285111-86d4d700-c2ef-11eb-94b4-a86faa9532e8.png)

**Comment by letuananh** [comment]
Thank you @goodmami that was a nice catch. I'll fix this soon.

**Comment by letuananh** [comment]
This has been fixed in commit d2162ff1e5cc7c6a70adb346552f5d5b795d8c46 :)
